services:
  trader_bot:
    build: .
    container_name: hyper_ema_strategy_bot
    restart: unless-stopped
    volumes:
      # Пробрасываем папку data, чтобы видеть сгенерированные картинки (опционально)
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1 # Чтобы логи сразу появлялись в консоли
