services:

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis-data:/data

  bot:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      - LOG_DIR=/opt/app/logs
      - LOG_FILE=bot.log
    volumes:
      - ./logs:/opt/app/logs

volumes:
  redis-data:
